package com.example.myapplication.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * {@inheritDoc}
 */
public class CameraDao extends AbstractDao<Camera, Long> {

    public static final String TABLENAME = "CAMERA";

    /**
     * Properties of entity Camera.<br/>
     * Can be used for QueryBuilder and target-specific queries.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property DeviceId = new Property(1, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Ip = new Property(3, String.class, "ip", false, "IP");
        public final static Property Port = new Property(4, int.class, "port", false, "PORT");
        public final static Property Location = new Property(5, String.class, "location", false, "LOCATION");
        public final static Property IsOnline = new Property(6, boolean.class, "isOnline", false, "IS_ONLINE");
        public final static Property LastUpdate = new Property(7, long.class, "lastUpdate", false, "LAST_UPDATE");
    }

    public CameraDao(DaoConfig config) {
        super(config);
    }

    public CameraDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"CAMERA\" (" +
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," +
                "\"DEVICE_ID\" TEXT NOT NULL ," +
                "\"NAME\" TEXT," +
                "\"IP\" TEXT," +
                "\"PORT\" INTEGER NOT NULL ," +
                "\"LOCATION\" TEXT," +
                "\"IS_ONLINE\" INTEGER NOT NULL ," +
                "\"LAST_UPDATE\" INTEGER NOT NULL );");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CAMERA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Camera entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDeviceId());

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }

        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(4, ip);
        }
        stmt.bindLong(5, entity.getPort());

        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(6, location);
        }
        stmt.bindLong(7, entity.getIsOnline() ? 1L : 0L);
        stmt.bindLong(8, entity.getLastUpdate());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Camera entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDeviceId());

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }

        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(4, ip);
        }
        stmt.bindLong(5, entity.getPort());

        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(6, location);
        }
        stmt.bindLong(7, entity.getIsOnline() ? 1L : 0L);
        stmt.bindLong(8, entity.getLastUpdate());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public Camera readEntity(Cursor cursor, int offset) {
        Camera entity = new Camera(
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getString(offset + 1), // deviceId
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ip
                cursor.getInt(offset + 4), // port
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // location
                cursor.getShort(offset + 6) != 0, // isOnline
                cursor.getLong(offset + 7) // lastUpdate
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Camera entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIp(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPort(cursor.getInt(offset + 4));
        entity.setLocation(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsOnline(cursor.getShort(offset + 6) != 0);
        entity.setLastUpdate(cursor.getLong(offset + 7));
    }

    @Override
    protected final Long updateKeyAfterInsert(Camera entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(Camera entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Camera entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
}