package com.example.myapplication.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * {@inheritDoc}
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cameraDaoConfig;
    private final CameraDao cameraDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cameraDaoConfig = daoConfigMap.get(CameraDao.class).clone();
        cameraDaoConfig.initIdentityScope(type);

        cameraDao = new CameraDao(cameraDaoConfig, this);

        registerDao(Camera.class, cameraDao);
    }

    public void clear() {
        cameraDaoConfig.clearIdentityScope();
    }

    public CameraDao getCameraDao() {
        return cameraDao;
    }
}